// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://fglwecflhdypbwujndtb.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnbHdlY2ZsaGR5cGJ3dWpuZHRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI3MTk0MjcsImV4cCI6MjA0ODI5NTQyN30.qRvPM8hO1UHCvRFtX8ILwGzdV6bPe6UrDJ53XxVDHs0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);